[versions]
agp = "8.10.0"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"
androidx-activityCompose = "1.10.1"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.2.1"
androidx-core-ktx = "1.16.0"
androidx-espresso-core = "3.6.1"
androidx-lifecycle = "2.8.4"
androidx-material = "1.12.0"
androidx-test-junit = "1.2.1"
compose-plugin = "1.6.11"
core = "3.5.1"
itextpdf = "5.5.13.3"
javase = "3.5.1"
junit = "4.13.2"
kotlin = "2.2.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.6.3"
gitlive = "1.13.0"
kotlinxDatetime = "0.6.0"
ktorClientContentNegotiation = "3.2.3"
ktorClientCore = "3.2.3"
ktorClientIos = "3.2.3"
ktorClientOkhttp = "3.2.3"
ktorSerializationKotlinxJson = "3.2.3"
napier = "2.6.1"
pdfbox = "2.0.29"
resources = "1.5.0"
voyager = "1.1.0-beta02"
settings-multiplatform = "1.3.0"
firebase-bom = "33.1.0"
zxingAndroidEmbedded = "4.3.0"
googleServices = "4.4.2"
skiko = "0.9.23"
coil3 = "3.3.0"
foundationDesktop = "1.7.0"

[libraries]
core = { module = "com.google.zxing:core", version.ref = "core" }
itextpdf = { module = "com.itextpdf:itextpdf", version.ref = "itextpdf" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
android-firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktorClientCore" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorClientOkhttp" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientContentNegotiation" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorSerializationKotlinxJson" }
ktor-client-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktorClientIos" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
resources = { module = "org.jetbrains.compose.resources:resources", version.ref = "resources" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager-tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }

settings = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "settings-multiplatform" }

# Firebase
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }

# Firebase Auth (Android)
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }

# Firebase Auth and Firebase Firestore (iOS via GitLive)

gitlive-firebase = { group = "dev.gitlive", name = "firebase", version.ref = "gitlive" }
gitlive-firebase-auth = { module = "dev.gitlive:firebase-auth", version.ref = "gitlive" }
gitlive-firebase-firestore = { group = "dev.gitlive", name = "firebase-firestore", version.ref = "gitlive" }

zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
zxing-javase = { module = "com.google.zxing:javase", version.ref = "javase" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
skiko = { module = "org.jetbrains.skiko:skiko-jetbrains-runtime", version.ref = "skiko" }
androidx-foundation-desktop = { group = "androidx.compose.foundation", name = "foundation-desktop", version.ref = "foundationDesktop" }



[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }